site_name: "MAGYC: Magnetometer and Gyroscope Calibration"
repo_url: https://github.com/srodriguez-mbari/magyclib
site_description: A novel method for the full three-axis magnetometer and three-axis Gyroscope bias estimation using angular rate measurements.
site_author: Sebastián Rodríguez - CoMPAS Lab - Monterey Bay Aquarium Research Institute.

nav:
  - "Introduction": "index.md"
  - "Proposed Methods":
    - "MAGYC-LS": "Proposed Methods/magyc_ls.md"
    - "MAGYC-NLS": "Proposed Methods/magyc_nls.md"
    - "MAGYC-BFG": "Proposed Methods/magyc_bfg.md"
    - "MAGYC-IFG": "Proposed Methods/magyc_ifg.md"
  - "Benchmark Methods":
    - "Ellipsoid Fit": "Benchmark Methods/ellipsoidfit.md"
    - "GTSAM magFactor3": "Benchmark Methods/magfactor3.md"
    - "Magnetometer Calibration Gyro Aided": "Benchmark Methods/magcalgyro.md"
    - "Sphere Fit": "Benchmark Methods/spherefit.md"
    - "TWOSTEP": "Benchmark Methods/twostep.md"

markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 2
            docstring_style: google
            show_root_toc_entry: false
            show_submodules: true
            merge_init_into_class: true
            show_signature_annotations: false


theme:
  name: material
  palette:
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Light mode
    - scheme: light
      media: "(prefers-color-scheme: light)"
      primary: blue grey
      toggle:
        icon: material/weather-night
        name: Dark mode

watch:
  - magyc/